# Generated by Django 3.0.8 on 2020-08-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variation_category'),
        ('carts', '0005_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Variations',
            field=models.ManyToManyField(blank=True, null=True, to='products.Variation'),
        ),
    ]
