# Generated by Django 3.0.8 on 2020-08-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Variations',
            new_name='variations',
        ),
    ]
